### PR TITLE
Move affecting type hints from symfony - Laravel 11 support 

### PR DESCRIPTION
**Pull request by rdeutz**
Fix for issue #42 

Moving the type hint at the end of the function.

Borrowed the code from [terax6669](https://github.com/terax6669) just to move forward.

### CODE REVIEW

**Comment by rdeutz** [comment]
@specialtactics Do you have an idea, when you can merge this and make a release?

**Review by specialtactics — APPROVED** [review]

**Comment by specialtactics** [comment]
Done @rdeutz I'll tag it as next feature version.

**Comment by specialtactics** [comment]
Actually tagged as 4.2.1, as this is more of a fix.

**Comment by specialtactics** [comment]
This seems to be a regression that broke morph functionality, I am in the process of fixing it.

**Pull request merged**
