### PR TITLE
Add Laravel 9 support

### PR DESCRIPTION
**Pull request by christoph-kluge**
### Description

In general tests look good for L9 + PHP8+ but changes are not backward compatible

### Waiting for dependent packages

* https://github.com/dingo/blueprint/pull/90

### Tests overview

* ❌  Laravel 8 + PHP 7.4.15 (fail due to php incompatible function calls)
* ❌  Laravel 8 + PHP 8.0.15 (2 tests break because of mismatching type - symfonys repsonse `getContent()` changed return behavior)
* ❌ Laravel 8 + PHP 8.1.2 (fail due to php incompatible function calls)
* ✅ Laravel 9 + PHP 8.0.15
* ✅ Laravel 9 + PHP 8.1.2

### Install instructions

Test and install this locally first. Thanks to @tobias-kuendig for sharing the instructions.

> composer.json:
> 
> ```json
>     "repositories": [
>         {
>             "type": "vcs",
>             "url":  "https://github.com/christoph-kluge/dingo-api"
>         },
>         {
>             "type": "vcs",
>             "url":  "https://github.com/dmason30/blueprint"
>         }
>     ],
> ```
> 
> Then require the package like so:
> 
> ```shell
> composer require api-ecosystem-for-laravel/dingo-api dev-laravel-9-support
> ```

### CODE REVIEW

**Comment by christoph-kluge** [comment]
I have never worked with travis - so here are my local test results. In general test look good for L9 + PHP8+ but changes are not backward compatible.

* ❌  Laravel 8 + PHP 7.4.15 (fail due to php incompatible function calls)
* ❌  Laravel 8 + PHP 8.0.15 (2 tests break because of mismatching type - symfonys repsonse `getContent()` changed return behavior)
* ❌ Laravel 8 + PHP 8.1.2 (fail due to php incompatible function calls)
* ✅ Laravel 9 + PHP 8.0.15
* ✅ Laravel 9 + PHP 8.1.2

**Comment by christoph-kluge** [comment]
This addresses #15 #16 #17

**Comment by suguer** [comment]
now  laravel9 illuminate/routing version is 9.0 but dingo-api just require ^7.0|^8.0 
how can i fix it

**Comment by christoph-kluge** [comment]
@suguer without further details it's hard to tell. My first quess: You're using the wrong version and/or fork.

Did you add my fork as repository to your `composer.json`?

https://getcomposer.org/doc/05-repositories.md

**Comment by suguer** [comment]
@christoph-kluge 
Did you add my fork as repository to your composer.json?    no , I do not change my composer.json  anything 


this is my full command output
----------------------------------------------------------
Using version ^3.1 for api-ecosystem-for-laravel/dingo-api
./composer.json has been updated
Running composer update api-ecosystem-for-laravel/dingo-api
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires api-ecosystem-for-laravel/dingo-api ^3.1 -> satisfiable by api-ecosystem-for-laravel/dingo-api[v3.1.0, v3.1.1].
    - api-ecosystem-for-laravel/dingo-api[v3.1.0, ..., v3.1.1] require illuminate/routing ^7.0|^8.0 -> found illuminate/routing[v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but it conflicts with your root composer.json require (^9.0).

You can also try re-running composer require with an explicit version constraint, e.g. "composer require api-ecosystem-for-laravel/dingo-api:*" to figure out if any version is installable, or "composer require api-ecosystem-for-laravel/dingo-api:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by christoph-kluge** [comment]
I see. So without changing your composer you'll be not able to test my fork. This pull-request is just a proposal to this library and does not necessarily mean that the maintainers will merge it.

If you want to **test** my non-official fork then you should to explicitly define this in your composer.json.

https://getcomposer.org/doc/05-repositories.md#loading-a-package-from-a-vcs-repository

**Comment by suguer** [comment]
ok. take the liberty to ask .what parameters should I write to composer.json . 
I don't know how to write composer.json very well
thx very much

**Comment by suguer** [comment]
@christoph-kluge 
excuse me , can you teach me how to write to composer.json . 
I try it, but failure

**Comment by christoph-kluge** [comment]
@suguer please check out the last link to the composer documentation how to load a package from vcs. You need my fork's github-url and the branch name. You can find this information on top of this page right below the title of the PR and replace the values in these examples.

If you click on my source branch you'll get redirected to my fork's URL and the branch. `https://github.com/christoph-kluge/dingo-api` and `laravel-9-support`. It's important to prefix `dev-{branchname}` as mentioned in the documentation.

**Comment by suguer** [comment]
okk, my composer.json is right , but still failed

when i run  "composer update"
------
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires api-ecosystem-for-laravel/dingo-api dev-laravel-9-support -> satisfiable by api-ecosystem-for-laravel/dingo-api[dev-laravel-9-support].
    - api-ecosystem-for-laravel/dingo-api dev-laravel-9-support requires dingo/blueprint dev-patch-1 -> found dingo/blueprint[dev-chore/laravel-7-compat, dev-master, v0.1.0, ..., v0.4.3] but it does not match the constraint.

**Comment by Endy-c** [comment]
When could this pull request be merged?

**Comment by tobias-kuendig** [comment]
For anyone trying to get @christoph-kluge's PR working locally before it being merged, you need to add these to your composer.json:

```json
    "repositories": [
        {
            "type": "vcs",
            "url":  "git@github.com:christoph-kluge/dingo-api.git"
        },
        {
            "type": "vcs",
            "url":  "git@github.com:dmason30/blueprint.git"
        },
        {
            "type": "vcs",
            "url": "https://github.com/annuh/fractal.git"
        }
    ],
```

Then require the package like so:

```bash
composer require api-ecosystem-for-laravel/dingo-api dev-laravel-9-support
```

**Comment by Endy-c** [comment]
> For anyone trying to get @christoph-kluge's PR working locally before it being merged, you need to add these to your composer.json:
> 
> ```json
>     "repositories": [
>         {
>             "type": "vcs",
>             "url":  "git@github.com:christoph-kluge/dingo-api.git"
>         },
>         {
>             "type": "vcs",
>             "url":  "git@github.com:dmason30/blueprint.git"
>         },
>         {
>             "type": "vcs",
>             "url": "https://github.com/annuh/fractal.git"
>         }
>     ],
> ```
> 
> Then require the package like so:
> 
> ```shell
> composer require api-ecosystem-for-laravel/dingo-api dev-laravel-9-support
> ```

solved!
extremely grateful!

**Comment by christoph-kluge** [comment]
@tobias-kuendig thank you for adding this here. 

I did change the repository-urls from `git@` to `https://` and added your install instructions to the MR description.

**Comment by tdavidsonas88** [comment]
`composer update` passed without errors for me with this guide. Nice! :tada: The downside that on my project all requests I have gives me 500 Internal Server Error without any backtrace message now. So gonna debug it.

**Comment by xtieume** [comment]
Not working with Fractal

**Comment by prady00** [comment]
When are we merging this PR?

**Comment by minkbear** [comment]
Waiting this as well

**Comment by specialtactics** [comment]
Hey all, sorry for the wait - I've been absent due to first holiday in 3.5 years, you know how it is :cry: 

Now that this is in a group though, I am able to and would be happy to give access to people who are committed and able to help maintain this package - please let me know if you are interested!

**Comment by specialtactics** [comment]
Just some updates for versions, https://github.com/api-ecosystem-for-laravel/dingo-api/pull/22

Please use tag v4.0.0 to get all the latest changes for laravel 9

**Comment by christoph-kluge** [comment]
@specialtactics I would be interested. Would you be up for a chat regarding short/mid/long-term plans for this lib? Can I reach you in some slack/discord channel?

Back in the days laravel was missing a lot of api-related features. Since then a lot changed and we might reduce a bit of boilerplate within this package.

**Comment by specialtactics** [comment]
Yes @christoph-kluge I agree, are you on the main laravel slack by any chance?

**Pull request merged**
