### PR TITLE
feat: add support for Laravel 10

### PR DESCRIPTION
**Pull request by patoui**
Description
----
Adds support for Laravel 10, ran some tests locally on Laravel 10 (10.0.3/10.6.2) with PHP 8.1 (8.1.12), no errors occurred. 🚀 

There is an accompanying pull requests to update `dingo/blueprint` which can be found here https://github.com/dingo/blueprint/pull/91

To test this locally:
- create a new Laravel 10 project
- create a `packages` directory
- clone the fork into the packages directory `cd packages && git clone https://github.com/patoui/dingo-api`
- within the new Laravel 10 project, update the `composer.json` with
```json
    "repositories": [
        {
            "type": "path",
            "url": "../packages/*/"
        }
    ],
    "require": {
        "api-ecosystem-for-laravel/dingo-api": "dev-master"
     },
    "minimum-stability": "dev"
```
- now within the Laravel 10 project directory run `rm -rf composer.lock vendor && composer update`

Now you can test `dingo-api` as you normally would!

EDIT: Updated instructions and `composer.json` latest tagged version from [dingo/blueprint](https://github.com/dingo/blueprint/releases/tag/v0.4.5)

### CODE REVIEW

**Comment by patoui** [comment]
@christoph-kluge / @specialtactics could either of you please review this PR? 🙏🏻

**Comment by nasrulhazim** [comment]
hopes this PR get approved soon. Been upgrading some of my project that rely on this package.

**Comment by hypervision-am** [comment]
Looking forward to the update

**Review by LordXaart — DISMISSED** [review]

**Comment by christoph-kluge** [comment]
@patoui thanks for adding L10 support here. Much appreciating your effort here 🚀 

https://github.com/dingo/blueprint/pull/91 needs to be merged, released and changed in the composer.json before I can continue on this MR.

**Comment by patoui** [comment]
@hesomp  waiting on the related PR to be merged, no response from maintainers yet

https://github.com/dingo/blueprint/pull/91#issuecomment-1472286487

**Review by ABouchard55 — APPROVED** [review]

**Comment by stueynet** [comment]
yay! https://github.com/dingo/blueprint/pull/91 was merge 🚀 🚀 . Can we get this one merged next? Thanks so much for everyone's hard work here.

**Comment by patoui** [comment]
I'll run some test this evening with the new tagged version from dingo/blueprint and push an update for `composer.json` here if no issues are found 😃

**Comment by patoui** [comment]
@christoph-kluge I've update the `composer.json` and re-tested, please review when you have time 🙏🏻 🙇🏻 

Ran some additional tests on Laravel 9 and 10 (PHP 8.1.2). Setup some API endpoints with basic auth, didn't run into any issues 👌🏻 

image
image

**Comment by softwareok1** [comment]
@christoph-kluge @ABouchard55 @LordXaart 
Hi any chance to get a reaction here? We need this for some migration projects and it's the only braking change to finish our work. Greetz.

**Comment by slaff** [comment]
@christoph-kluge @ABouchard55 @LordXaart any chance of merging this PR?

**Review by specialtactics — APPROVED** [review]

**Comment by specialtactics** [comment]
Apologies for delay again, I have been away until last week. Thanks for the PR @patoui, merged and tagged as v4.1.0

**Comment by patoui** [comment]
Thank you so much @specialtactics , very much appreciated 🙏🏻 🙇🏻

**Pull request merged**
